# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20161128_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.Category'),
            preserve_default=False,
        ),
    ]
